### ISSUE TITLE
Installation in sub-folder

### ISSUE THREAD

**Issue by robwent** [saelos/saelos#13]
I just tried installing on a localhost to test at http://localhost:8080/saelos/

The default htaccess file redirects `http://localhost:8080/saelos/public/` to `http://localhost:8080/login`

I tried the following, copying a working wordpress site:

    RewriteBase /saelos/public/
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /saelos/public/index.php [L]

I can access the login page and I then get a 404 for `http://localhost:8080/api/v1/auth/login` after trying to log in.

Looking at the headers, it's not being redirected, so maybe something in the app that's rewriting the browser url?

EDIT: It's nothing to do with the htaccess file, the same thing happens with the original rules.

- [ ] Need to calculate base_url from the window.location @ https://github.com/saelos/saelos/blob/staging/resources/assets/js/utils/Http.js#L8

**Comment by dbhurley** [comment]
Why not map to a subdomain instead? That's far more secure, and allows for the proper use of a `public` folder. We haven't done much testing on subfolder structure, as you can tell.

**Comment by robwent** [comment]
It was just a quick local test to see how it works, security isn't really an issue.
I generally install all my testing sites in one folder on a local host. Joomla, Wordpress, Drupal ( and frameworks Laravel, Symfony, Yii) all work without any problems.

I'll give it a go on a live server when I get the time.

**Comment by michelegarcia** [comment]
@dbhurley I tried your installation tutorial on youtube and it didn't work. All I see when I type the link (http://glaucefernandes.com.br/saelos/) are the files in the directory. Is this really a bug or it's my server?

**Comment by robwent** [comment]
@michelegarcia The files should go under the root of your domain. The public folder is where the application runs.

You can disable directory browsing by adding `Options -Indexes` to your .htaccess file.

**Comment by dongilbert** [comment]
This line is the main reason that Saelos won't work in a subdirectory - https://github.com/saelos/saelos/blob/staging/resources/assets/js/utils/Http.js#L10

We need to determine from the current page / document.location what the base url for the API should be.

**Comment by robwent** [comment]
Can't the base url be set during installation?

**Comment by dongilbert** [comment]
@robwent Can you pull the latest code for Saelos and try the install in a subfolder? Should be working now as I pushed a fix for the code that was breaking the API requests when installed in a subfolder.

**Comment by robwent** [comment]
I just downloaded the staging branch, ran composer install but if failed with:

    Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by robwent** [comment]
If I install the latest release I get the install screen, but if I overwrite with the latest files I get a 500 error. Same if I run composer.

**Comment by robwent** [comment]
I think mabe @php only works on some systems where an alias is set up?

**Comment by eddiecsilva** [comment]
Hello! I was also interested in testing the solution, but ran into the same problem of not being able to install on a local server. 

This is undoubtedly the most common way to test something to know the functions before creating a real homologation environment. 

I hope this feature will work in future releases.
