### ISSUE TITLE
Can not create contact notes

### ISSUE THREAD

**Issue by AndrassGray** [saelos/saelos#15]
On the contact screen's sidebar panel, I can enter text in the notes fields, but this text is not stored.

**Comment by dbhurley** [comment]
Confimed, working on this.

**Comment by dongilbert** [comment]
@AndrassGray thanks for the report. Notes management was modified in beta 3. Give it a try and file another issue of the problem persists.

https://github.com/saelos/saelos/commit/c83fdfa791735c6c5c06c0d0159d181e2b9e36a5

**Comment by AndrassGray** [comment]
Working fine. And the layout is much nicer as well. 

Not worth a new issue, but maybe you could strip the html from the display. My note is between <p>..</p>.
