### ISSUE TITLE
No fields after fresh beta 4 install?

### ISSUE THREAD

**Issue by ronnieduke** [saelos/saelos#25]
![image](https://user-images.githubusercontent.com/742579/39075227-93708418-44a9-11e8-8ebd-09d217b65564.png)

**Comment by dbhurley** [comment]
We need to check your roles (menu has nothing) usually means that you don't have any config level access (manager/admin).

**Comment by dongilbert** [comment]
From your command line, run:
```
php artisan tinker

**Comment by ronnieduke** [comment]
@dongilbert - sorry for the delay. It seems my php artisan is still messed up somehow. Getting the error `SQLSTATE[HY000] [1045] Access denied for user 'saelos'@'localhost' (using password: NO) (SQL: select * from `roles`)` despite that is the same user account I use to login to Saelos just fine.

**Comment by dongilbert** [comment]
Addressed with the migration fixes in Beta 5.
