### ISSUE TITLE
required fields when creating a contact (somewhat strangely) broken

### ISSUE THREAD

**Issue by AndrassGray** [saelos/saelos#26]
In beta-4 :

On first impression, only the email-field is required.

I just enter an email and hit save : Nothing.
I add a last-name, hit save : Nothing.
I add a first-name, hit save : Nothing.

Cancel. New try :

I just enter an email and hit save : Nothing.
I enter first-name and last-same, hit save : Ok.

**Comment by dbhurley** [comment]
Thanks, taking a look at this.

**Comment by dongilbert** [comment]
There was a bug with the way custom fields were being populated into the contact records before saving that caused an issue in beta-4 & in certain cases beta-5 as well. Fixed via 66e87f5c66abdde75c06a580d39192c1b16442b6 which will be part of beta-6.
