### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sakiss** [saelos/saelos#27]
I followed the installation instructions:

>     Download the latest release from the releases tab.
>     Unzip in a web accessible directory. 
>     Navigate to your site.

But when i navigate to the site i can only see the contents of the saelos folder, in my server.
Checking that with:

- apache2
- php  7.1
- MySQL 5.6

Am i missing something?

**Comment by dbhurley** [comment]
Check your `public` folder. Your htaccess should direct traffic to this directory.

**Comment by sakiss** [comment]
You mean that i should add an .htaccess to the root of the saelos dir that redirects to the public folder?
What if i "call" the public dir from my browser?

**Comment by dbhurley** [comment]
It should be doing this already, so you should make sure your server is reading your htaccess files correctly, but yes, should be able to navigate there.
