### ISSUE TITLE
Post Installation message

### ISSUE THREAD

**Issue by sakiss** [saelos/saelos#28]
After the installation is finished i am getting this message: "There is no column with name 'avatar' on table 'users'. "
Indeed i checked the table _users_ and has no _avatar_ column

Do note: This is displayed within the app's screen and not as a php error

1.0-beta-4

**Comment by dbhurley** [comment]
Thanks for pointing this out. I pulled the avatar functionality at the last minute from beta due to a problem with the uploader. I'll make sure it's fixed and available by Stable.

**Comment by ChrisRAoW** [comment]
Same issue still exists in beta-5

**Comment by dbhurley** [comment]
Well that's certainly frustrating! Same error message? Can you check what tables were created in the database?

**Comment by ChrisRAoW** [comment]
Everything seems to be there, but the avatar column is missing the the users table. Used the saelos_full_install.tar.gz of beta-5.

**Comment by dbhurley** [comment]
Okay, I'll be on this today, so I'll let you know what I uncover! Thanks for your patience and for reporting this back to me so I can get it fixed!

**Comment by ChrisRAoW** [comment]
I checked out the migrations and the avatar column is never created. Hope it helps ;-)

**Comment by ChrisRAoW** [comment]
Oh, and BTW. After installation I can't create any contact, company or opportunity. When I try to it seems that the screen is freezing (overlay with opacity) and I can't do anything. Not sure if it is related.

**Comment by dbhurley** [comment]
Well thats good, because it shouldn't be at this point. We removed the failing migration point.

**Comment by dongilbert** [comment]
We messed up the packaging for the first release of beta-5 and didn't include the latest commits. This was addressed a day or so after the release when we repackaged and re-released beta-5.
