### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by sakiss** [saelos/saelos#30]
When i access saelos entry page, it redirects me to the login page, but i cannot login due to the fact that the called ajax request url, is out of the saelos scope.

Steps to reproduce:
1. Access the saelos entry point in your browser. In my case http://localhost/saelos or http://localhost/saelos/public

2. The login page displays but the url changes to http://localhost/login

3. Pressing the submit button in the login form gives a 404 response to the ajax request.
Request URL: http://localhost/api/v1/auth/login , Response code: 404

Tested in:
Ubuntu 14.0.4
Apache2
Php 7.1

Btw. The server's configuration is the default and i also run instances of Joomla, Magento and other apps without any issue

**Comment by wwooley** [comment]
+1 Same here.
Linux Centos 7.4 
MariaDB 10.2.14
PHP 7.2
Apache 2.4

Had same issue on Beta 3.  Just installed Beta 4 this morning with same results as sakiss, with exception that I get no result or error redirect.
Is on my live server which hosts multiple websites using Joomla, RETS/IDX feeds, etc.

Thanks...

**Comment by sakiss** [comment]
Yes I am on beta4.
Wesley I am not getting any error message in the page. The 404 error is in the Ajax response

**Comment by dongilbert** [comment]
The way the app is currently written, it's not meant to handle subfolder installs (that's why we have a `/public` directory that should be set as your web root). It's on our list of things to address. Thanks for the report.

**Comment by dongilbert** [comment]
Related to #13. Let's keep any subfolder install related questions/comments to that issue. :)
