### ISSUE TITLE
Registration page not sending registration email...

### ISSUE THREAD

**Issue by tallship** [saelos/saelos#35]
Hello,

Upon attempting to register at https://saelos.org it allows me to create an account, but then I don't even see in my SMTP logs that the email was received.

Also, upon going back, it allowed me to register the same email address again, and then still... no email received with the further instructions.

**Comment by dongilbert** [comment]
Thanks for the report, but please send website issues for saelos.org to the #general Slack channel at https://join.slack.com/t/saelos/shared_invite/enQtMzQ3MTA2MTc4OTMzLWNlYjU1MGU2YmZhY2E4Y2Q0MmQyMjkwN2JmNjRiMjcyMGYyZjgwMGYxZGI4ZWMyOTA5MGUxNWI2Y2I5Y2U3YjU
