### ISSUE TITLE
New Opportunity date/time pickers start at 1970-01-01 and cannot be edited manually

### ISSUE THREAD

**Issue by proffalken** [saelos/saelos#37]
*Bug:* The date/time picker when creating a new opportunity starts at 1970-01-01.  You then have to click through each month until you reach the current year.

*Example:*
![newopportunity](https://user-images.githubusercontent.com/262545/39448582-3c36b8d6-4cbd-11e8-8970-3f9348f0eceb.png)

*Proposal:* That the default date/time should be `now()` so that the user can adjust as needed without having to click past every month for the past 50 years!

**Comment by dongilbert** [comment]
😬 - sorry. This is a known issue. I need to work out sensible default dates when working with empty values on new / edited items. That'll be addressed soon. Thanks for the report!

**Comment by proffalken** [comment]
Grand so, thanks for the quick response, I'll update with the next release :)
