### ISSUE TITLE
unzip problem

### ISSUE THREAD

**Issue by micker** [saelos/saelos#38]
hello when i try to unzip installation package i have an error about relative link ....i can't install it
(windows 10, 7 zip)

**Comment by dbhurley** [comment]
What program are you using to unzip (and I assume you're downloading the .tar.gz full package?)

**Comment by micker** [comment]
yes for tar.gz
i use 7zip opensource compressor on w10 (i try in 2 diff computer)
https://www.7-zip.org/

**Comment by kirashi3** [comment]
The 1.0-beta-5 install tar.gz is unzipping fine on my Windows 10 system using version 16.04 of 7-zip.

**Comment by dongilbert** [comment]
Thanks for the report, but please send support style questions (anything not really code related) to the #general channel on the Saelos slack - https://join.slack.com/t/saelos/shared_invite/enQtMzQ3MTA2MTc4OTMzLWNlYjU1MGU2YmZhY2E4Y2Q0MmQyMjkwN2JmNjRiMjcyMGYyZjgwMGYxZGI4ZWMyOTA5MGUxNWI2Y2I5Y2U3YjU
