### ISSUE TITLE
Error running php artisan list

### ISSUE THREAD

**Issue by luizeof** [saelos/saelos#4]
When running php artisan list I got this error on console:

Error log:

PHP Fatal error:  Declaration of App\Contact::setCustomFieldValue(string $alias, $value): App\ModelTraits\void must be compatible with App\Contracts\HasCustomFieldsInterface::setCustomFieldValue(string $alias, $value): App\Contracts\void in /var/lib/docker/volumes/saelos12/_data/app/Contact.php on line 31

In Contact.php line 31:

  Declaration of App\Contact::setCustomFieldValue(string $alias, $value): App\ModelTraits\void must be compatible with App\Contracts\HasCustomFieldsInterface::set
  CustomFieldValue(string $alias, $value): App\Contracts\void

**Comment by AlanRezende** [comment]
Mine gives a similar error also on Contact.php:31

I have unzipped in my server and when I try to access on chrome I get the `Whoops, looks like something went wrong.` message.

When I checked the `laravel.log` I got

`
production.ERROR: Declaration of App\Contact::setCustomFieldValue(string $alias, $value): App\ModelTraits\void must be compatible with App\Contracts\HasCustomFieldsInterface::setCustomFieldValue(string $alias, $value): App\Contracts\void {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Declaration of App\\Contact::setCustomFieldValue(string $alias, $value): App\\ModelTraits\\void must be compatible with App\\Contracts\\HasCustomFieldsInterface::setCustomFieldValue(string $alias, $value): App\\Contracts\\void at /saelos/app/Contact.php:31)
`

**Comment by dbhurley** [comment]
Okay, hold on, looking into this.

**Comment by AlanRezende** [comment]
Sorry @dbhurley my Contact.php:31 was solved by using the right version of PHP (7.1)

Now I can make the install but at the end in /install/final I get the error in #5

**Comment by dbhurley** [comment]
Ah! 👍 @luizeof Can you check for the same thing?

**Comment by luizeof** [comment]
fixed with 7.1
