### ISSUE TITLE
I get "Authentication Error" at login after installation 

### ISSUE THREAD

**Issue by PointfullDevelopers** [saelos/saelos#6]
I installed everything as the instructions but I'm unable to login

The form gives me authentication error but my credentials are correct

**Comment by AndrassGray** [comment]
Same here.

As a secondary remark, the checkbox for "Remember me on this computer" is missing.

**Comment by dbhurley** [comment]
On it, thanks for reporting.

**Comment by dongilbert** [comment]
@andrassgray - thanks for the report. Beta 3 was released today with some fixes around this. Some server setups wouldn’t allow for proper auth to the api. Please file another issue if the problem persists after beta-3
