### ISSUE TITLE
undefined constant in config/imap.php 

### ISSUE THREAD

**Issue by blairbo** [saelos/saelos#65]
Bug report
#
Saelos Version: 1.0   ##RC
PHP Version: 7.2

[https://github.com/saelos/saelos/blame/staging/config/imap.php#L105](url)

-403 error on fresh install from [https://github.com/saelos/saelos/releases/download/1.0-RC/saelos_full_install.tar.gz](url)
-no .htaccess file generated
-tried to hit /public and got this error: "Warning: Use of undefined constant FT_UID - assumed 'FT_UID' (this will throw an Error in a future version of PHP) in /var/www/html/config/imap.php on line 105"

Log errors: 

[https://pastebin.com/f0Mk4Vwh](url)

**Comment by dongilbert** [comment]
Saelos requires the `ext-imap` module for php.

Also, you should map your web root to the /public folder in the saelos root directory.
